name: formating and checking code

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  lint:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for formatting changes
        run: |
          git status --porcelain | grep -qE '( M | A )'  # Check for modified or added files
          if [ $? -eq 0 ]; then
            echo "Formatting changes detected, committing..."
          else
            echo "No formatting changes detected, skipping commit."
            exit 0  # Exit with success code (0) to avoid job failure
          fi
      - name: install dependencies
        run: npm install
      
      - name: format code
        run: npm run prettier

      - name: linter
        run: npx eslint

      - name: Configure Git (Only if changes detected)
        if: steps.check-for-formatting-changes.outputs == ''
        run: |
          git config --local user.name "franklin rodriguez"
          git config --local user.email "franklinserif@gmail.com"

      - name: Add changes (Only if changes detected)
        if: steps.check-for-formatting-changes.outputs == ''
        run: git add .

      - name: Commit changes (Only if changes detected)
        if: steps.check-for-formatting-changes.outputs == ''
        run: git commit -m "Format code and fix linting issues"

      - name: Push changes (Only if changes detected)
        if: steps.check-for-formatting-changes.outputs == ''
        run: git push origin HEAD